---
run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - typecheck
    - errcheck
    - lll
    - ineffassign
    - staticcheck
    - sqlclosecheck
    - rowserrcheck
    - prealloc
    - gocyclo
linters-settings:
  goimports:
    local-prefixes: vezu-saas
