// Code generated by tygo. DO NOT EDIT.

//////////
// source: stats.go

export interface GetMostUsedDomainsRequest {
  range: string;
  categories: string[];
  tzOffset: number /* int */;
}
export interface GetMostUsedDomainsResponse {
  domain: string;
  count: number /* int */;
}
export interface GetServerUsageByTimeRangeRequest {
  range: string;
  categories: string[];
  tzOffset: number /* int */;
}
export interface GetServerUsageByTimeRangeResponse {
  timeRange: string;
  count: number /* int */;
}
