// Code generated by tygo. DO NOT EDIT.

//////////
// source: stats.go

export interface GetMostUsedDomainsRequest {
  range: string;
  categories: string[];
}
export interface GetMostUsedDomainsResponse {
  domain: string;
  count: number /* int */;
}
