// Code generated by tygo. DO NOT EDIT.

//////////
// source: stats.go

export interface GetMostUsedDomainsRequest {
  from: number /* int64 */;
  to: number /* int64 */;
  categories: string[];
}
export interface GetMostUsedDomainsResponse {
  domain: string;
  count: number /* int */;
}
export interface GetServerUsageByTimeRangeRequest {
  from: number /* int64 */;
  to: number /* int64 */;
  categories: string[];
}
export interface GetServerUsageByTimeRangeResponse {
  timeRange: string /* RFC3339 */;
  count: number /* int */;
}
