---
name: Build backend image and create PR

on:
  push:
    branches:
      - main
      - set-created-pr-name
    paths:
      - backend/**
      - Dockerfile-web-backend
      - .github/workflows/backend-web-build.yaml

jobs:
  build-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Split title for PR
        id: split-title
        run: |
          echo "pr-title=$(echo ${{ github.event.push.head_commit.message }} | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-east1-docker.pkg.dev/oriontec-422114/oriondns/backend-web
          tags: |
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          file: Dockerfile-web-backend
          tags: ${{ steps.meta.outputs.tags }}

      - uses: actions/checkout@v4
        with:
          repository: orion-tec/k8s-state
          token: ${{ secrets.GH_PAT }}
          path: k8s-state

      - name: Update deployment
        run: |
          sed -i "s|image: us-east1-docker.pkg.dev/oriontec-422114/oriondns/backend-web:.*|image: ${{ steps.meta.outputs.tags }}|g" k8s-state/testing/12-oriondns.yaml

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: ${{ steps.split-title.outputs.pr-title }}
          title: ${{ steps.split-title.outputs.pr-title }}
          body: ${{ steps.split-title.outputs.pr-title }}
          branch: ci-update-backend-${{ github.sha }}
          base: main
          labels: ci
          path: k8s-state
